LOAD DATA LOCAL INFILE 'sport.txt' INTO TABLE Sport;
LOAD DATA LOCAL INFILE 'marche.txt' INTO TABLE Marche;

--  LOAD DATA LOCAL INFILE 'utenti.txt' INTO TABLE Utenti;
-- LOAD DATA LOCAL INFILE 'prodotti.txt' INTO TABLE Prodotti;
